### ISSUE TITLE
Snap - Numpad Enter camera zoom zooms game in a bit higher than the game's default camera

### ISSUE THREAD

**Issue by TheShadowHat** [Chasmical/Sands#1]
Reproduce Steps
Step 1: To double check, open the game, set the zoom level to something absurd, then quit
Step 2: Once you're in game with the zoom set to the game's default, press Numpad Enter. The camera will zoom in.

Admittedly this is very minor and is circumvented by literally just remembering to zoom in again but /shrug

**Comment by Chasmical** [comment]
## ⚰️ [S&S] Short and Simple has been discontinued ⚰️

The project's repository is archived as part of the GitHub Archive Program. [S&S] Short and Simple's code and the documentation will no longer be updated. See more information in the [latest RogueLibs blog post](https://chasmical.github.io/RogueLibs/blog/2024/02/03/discontinuing-roguelibs). Feel free to fork the repository to continue working on the project.

**Comment by Chasmical** [comment]
although, I think I may have already fixed this issue, and I just forgot to close it
